<?php
#
# xPyrus - Framework for Community and knowledge exchange
# Copyright (C) 2003-2008 UniHelp e.V., Germany
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, only version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see http://www.gnu.org/licenses/agpl.txt
#
$globalSettings = array();
$globalSettings['ENTRY_MAX_LENGTH_RAW'] = '20000';
$globalSettings['ENTRY_MAX_SMILEYS'] = '40';
$globalSettings['ENTRY_MAX_INLINE_IMAGES'] = '20';
$globalSettings['ENTRY_MAX_ATTACHMENT_SIZE_CUMMULATED'] = '200';
$globalSettings['ENTRY_MAX_ATTACHMENT_SIZE'] = '100';
$globalSettings['ENTRY_BLOG_MAX_ATTACHMENT_SIZE_CUMMULATED'] = '500';
$globalSettings['ENTRY_BLOG_MAX_ATTACHMENT_SIZE'] = '200';
$globalSettings['ENTRY_NEWS_MAX_ATTACHMENT_SIZE'] = '250';
$globalSettings['ENTRY_NEWS_MAX_ATTACHMENT_SIZE_CUMMULATED'] = '500';
$globalSettings['COURSE_MAX_FILE_SIZE'] = '10000';
$globalSettings['COURSE_SUBSIDIES_MAX_FILE'] = '100';
$globalSettings['COURSE_SUBSIDIES_MAX_DOWNLOAD'] = '100';
$globalSettings['COURSE_SUBSIDIES_MAX_USER'] = '100';
$globalSettings['COURSE_SUBSIDIES_SUBVENTION'] = '2';
$globalSettings['COURSE_SUBSIDIES_ENABLED'] = 'f';
$globalSettings['MAX_LOGIN_ERRORS'] = '10';
$globalSettings['POINT_SOURCES_FLOW_MULTIPLICATOR'] = '10';
?>
