--
-- xPyrus - Framework for Community and knowledge exchange
-- Copyright (C) 2003-2008 UniHelp e.V., Germany
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as
-- published by the Free Software Foundation, only version 3 of the
-- License.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU Affero General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program. If not, see http://www.gnu.org/licenses/agpl.txt
--
-- some smileys
-- $Id: schema-smileys-initial-data.sql 6210 2008-07-25 17:29:44Z trehn $
--
-- generated via:
-- cat ../htdocs/images/smileys/smileys.txt | sed 's/.$//' | \
-- awk '{ if(NR>1) { print "INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) \
-- VALUES (#",$3,"#,#", $4,"#,#",$2,"#);";} }' | sed "s/# /'/g" | sed "s/ #/'/g" > schema-smileys-initial-data.sql

INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':-)',':)','smile.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':biggrin:',':D','biggrin.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':smileD:',':-D','smileD.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cool:','8-)','cool.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':laugh:',':))','laugh.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bubble:',':O','bubble.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':censored:','I)','censored.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':knuddel:',':knuddel:','knuddel.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wave:',':wave:','wave.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':confused:','?(','confused.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eek:','8o','eek.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':crying:',';(','crying.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':(',':-(','sad.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':motz:',':motz:','motz.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mad:','X(','mad.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':schimpf:',':schimpf:','schimpf.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':frown:',':frown:','frown.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':grimmig:',':grimmig:','grimmig.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':redface:',':redface:','redface.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kool:',':kool:','kool.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':aua:',':aua:','aua.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rotwerd:',':rotwerd:','rotwerd.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':heiligenschein:',':heiligenschein:','heiligenschein.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ka:',':ka:','ka.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tot:',':tot:','tot.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':crazy:',':crazy:','crazy.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':frech:',':frech:','frech.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lecker:',':lecker:','lecker.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pfui:',':pfui:','pfui.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':angst:',':angst:','angst.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':schande:',':schande:','schande.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lala:',':lala:','lala.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':konfus:',':konfus:','konfus.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':schuechtern:',':schuechtern:','schuechtern.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':shy:',':shy:','shy.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':naughty:',':naughty:','naughty.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tongue:',':tongue:','tongue2.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':muede:',':muede:','muede.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':danger:',':danger:','danger.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':baeh:',':baeh:','baeh.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':loveyou:',':loveyou:','loveyou.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':klatsch:',':klatsch:','klatsch.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':chinese:',':chinese:','chinese.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rofl:',':rofl:','rofl.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lol:',':lol:','lol.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':haha:',':haha:','haha.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hehe:',':hehe:','hehe.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lach:',':lach:','lach.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':schmoll:',':schmoll:','schmoll.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':heul:',':heul:','heul.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dream:',':dream:','dream.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gaehn:',':gaehn:','gaehn.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':explode:',':explode:','explode.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bounce:',':bounce:','bounce.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kotz:',':kotz:','kotz.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':peitsch:',':peitsch:','peitsch.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bang:',':bang:','bang.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':biene:',':biene:','biene.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hail:',':hail:','hail.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':trink:',':trink:','trink.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hippy:',':hippy:','hippy.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gruebel:',':gruebel:','gruebel.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':thumbs:',':thumbs:','thumbs.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':user:',':user:','user.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':respekt:',':respekt:','respekt.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wallbash:',':wallbash:','wallbash.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':handy:',':handy:','handy.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':krank:',':krank:','krank.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':applaudit:',':applaudit:','applaudit.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':think:',':think:','think.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gitarre:',':gitarre:','gitarre.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':knuddel2:',':knuddel2:','knuddel2.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hase:',':hase:','hase.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':herz:',':herz:','herz.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hicks:',':hicks:','hicks.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bier:',':bier:','bier.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':blume:',':blume:','blume.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':foto:',':foto:','foto.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':geschenk:',':geschenk:','geschenk.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kaffee:',':kaffee:','kaffee.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sleep:',':sleep:','sleep.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sm:',':sm:','sm.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sofa:',':sofa:','sofa.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':idea:',':idea:','idea.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hammer:',':hammer:','hammer.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ok:',':ok:','ok.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rot:',':rot:','rot.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wall:',':wall:','wall.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':good:',':good:','good.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bad:',':bad:','bad.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tele:',':tele:','tele.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':telefon:',':telefon:','telefon.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':male:',':male:','male.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':female:',':female:','female.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sperm:',':sperm:','sperm.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':flower:',':flower:','flower.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bluescreen:',':bluescreen:','bluescreen.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':birthday:',':birthday:','birthday.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':spion:',':spion:','spion.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':grunz:',':grunz:','grunz.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':schlumpf:',':schlumpf:','schlumpf.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':po:',':po:','po.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':clown:',':clown:','clown.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dancer:',':dancer:','dancer.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':devil:',':devil:','devil.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':king:',':king:','king.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':baby:',':baby:','baby.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':girl:',':girl:','girl.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':woman:',':woman:','woman.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':engel:',':engel:','engel.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':elvis:',':elvis:','elvis.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':freak:',':freak:','freak.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':alien:',':alien:','alien.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rauch:',':rauch:','rauch.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':liebe:',':liebe:','liebe.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bussi:',':bussi:','bussi.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':troest:',':troest:','troest.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':love:',':love:','love.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':prost:',':prost:','prost.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gunman:',':gunman:','gunman.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':shot:',':shot:','shot.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':asmd:',':asmd:','asmd.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rocket:',':rocket:','rocket.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sniper:',':sniper:','sniper.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':camper:',':camper:','camper.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':grenade:',':grenade:','grenade.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':target:',':target:','target.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':headshot:',':headshot:','headshot.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':instagib:',':instagib:','instagib.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rail:',':rail:','rail.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':P',':p','tongue.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zwinker:',';)','zwinker.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':buch:',':buch:','buch.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':juggle:',':juggle:','juggle.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':party:',':party:','party.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':traurig:',':traurig:','traurig.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nacht:',':nacht:','nacht.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':essen:',':essen:','essen.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nixweiss:',':nixweiss:','nixweiss.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':megaphon:',':megaphon:','megaphon.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ohjeh:',':ohjeh:','ohjeh.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':popcorn:',':popcorn:','popcorn.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':besserwisser:',':besserwisser:','besserwisser.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':peitsche:',':peitsche:','peitsche.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vertrag:',':vertrag:','vertrag.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':stop:',':stop:','stop.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sweetheart:',':sweetheart:','sweetheart.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nikolaus:',':nikolaus:','nikolaus.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ausrufezeichen:',':!:','ausrufezeichen.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':stark:',':stark:','stark.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lichtaus:',':lichtaus:','lichtaus.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':itchy:',':itchy:','itchy.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lernen:',':lernen:','lernen.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':meet:',':meet:','meet.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hug:',':hug:','hug.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hammerme:',':hammerme:','hammerme.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bath:',':bath:','bath.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fechten:',':fechten:','fechten.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pedro:',':pedro:','pedro.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lollol:',':lollol:','lollol.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':caipi:',':caipi:','caipi.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':suche:',':suche:','suche.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':handkuss:',':handkuss:','handkuss.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ot:',':ot:','ot.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':unschuldig:',':unschuldig:','unschuldig.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':grins:',':grins:','grins.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zunge:',':zunge:','zunge.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':icqsmile:',':icqsmile:','icqsmile.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':niko:',':niko:','niko.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (';-)',';-)','zwinker.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bauch:',':bauch:','bauch.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':huhn:',':huhn:','huhn.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tisch:',':tisch:','tisch.gif');
INSERT INTO  __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zerstoere_computer:',':zerstoere_computer:','zerstoere_computer.gif');

-- country smileys
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gs3:', ':gs3:', 'countries/gs3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sco3:', ':sco3:', 'countries/sco3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tl1:', ':tl1:', 'countries/tl1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mo2:', ':mo2:', 'countries/mo2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bz3:', ':bz3:', 'countries/bz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pw1:', ':pw1:', 'countries/pw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bi1:', ':bi1:', 'countries/bi1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bm1:', ':bm1:', 'countries/bm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gt1:', ':gt1:', 'countries/gt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ve3:', ':ve3:', 'countries/ve3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':az2:', ':az2:', 'countries/az2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tf3:', ':tf3:', 'countries/tf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':al1:', ':al1:', 'countries/al1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zm3:', ':zm3:', 'countries/zm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':np1:', ':np1:', 'countries/np1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fj1:', ':fj1:', 'countries/fj1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sn1:', ':sn1:', 'countries/sn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':br2:', ':br2:', 'countries/br2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ie1:', ':ie1:', 'countries/ie1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ru2:', ':ru2:', 'countries/ru2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sd3:', ':sd3:', 'countries/sd3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dz3:', ':dz3:', 'countries/dz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lc3:', ':lc3:', 'countries/lc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ua2:', ':ua2:', 'countries/ua2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mq3:', ':mq3:', 'countries/mq3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ie3:', ':ie3:', 'countries/ie3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eh3:', ':eh3:', 'countries/eh3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':to1:', ':to1:', 'countries/to1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bf1:', ':bf1:', 'countries/bf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bs2:', ':bs2:', 'countries/bs2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nl1:', ':nl1:', 'countries/nl1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jo2:', ':jo2:', 'countries/jo2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mq2:', ':mq2:', 'countries/mq2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':na2:', ':na2:', 'countries/na2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':id3:', ':id3:', 'countries/id3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nf2:', ':nf2:', 'countries/nf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bg3:', ':bg3:', 'countries/bg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gq2:', ':gq2:', 'countries/gq2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sb3:', ':sb3:', 'countries/sb3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tm2:', ':tm2:', 'countries/tm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tk1:', ':tk1:', 'countries/tk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ao3:', ':ao3:', 'countries/ao3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wf1:', ':wf1:', 'countries/wf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ad3:', ':ad3:', 'countries/ad3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':au2:', ':au2:', 'countries/au2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':om3:', ':om3:', 'countries/om3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cc3:', ':cc3:', 'countries/cc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':my1:', ':my1:', 'countries/my1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':yt1:', ':yt1:', 'countries/yt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':za3:', ':za3:', 'countries/za3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mw3:', ':mw3:', 'countries/mw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ba2:', ':ba2:', 'countries/ba2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tk3:', ':tk3:', 'countries/tk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cz1:', ':cz1:', 'countries/cz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sk3:', ':sk3:', 'countries/sk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tj1:', ':tj1:', 'countries/tj1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fk3:', ':fk3:', 'countries/fk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':li3:', ':li3:', 'countries/li3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vi1:', ':vi1:', 'countries/vi1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zw3:', ':zw3:', 'countries/zw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ke1:', ':ke1:', 'countries/ke1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wal3:', ':wal3:', 'countries/wal3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ve2:', ':ve2:', 'countries/ve2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gb2:', ':gb2:', 'countries/gb2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sz1:', ':sz1:', 'countries/sz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sa1:', ':sa1:', 'countries/sa1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mk2:', ':mk2:', 'countries/mk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ag2:', ':ag2:', 'countries/ag2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ar3:', ':ar3:', 'countries/ar3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sr2:', ':sr2:', 'countries/sr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gi1:', ':gi1:', 'countries/gi1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mt1:', ':mt1:', 'countries/mt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bz1:', ':bz1:', 'countries/bz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ga2:', ':ga2:', 'countries/ga2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':um1:', ':um1:', 'countries/um1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':io2:', ':io2:', 'countries/io2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hm3:', ':hm3:', 'countries/hm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bf2:', ':bf2:', 'countries/bf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tw1:', ':tw1:', 'countries/tw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':md2:', ':md2:', 'countries/md2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lr2:', ':lr2:', 'countries/lr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sd1:', ':sd1:', 'countries/sd1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':es3:', ':es3:', 'countries/es3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lt1:', ':lt1:', 'countries/lt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mg3:', ':mg3:', 'countries/mg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rw2:', ':rw2:', 'countries/rw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':az1:', ':az1:', 'countries/az1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nu2:', ':nu2:', 'countries/nu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sz2:', ':sz2:', 'countries/sz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':us2:', ':us2:', 'countries/us2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cl3:', ':cl3:', 'countries/cl3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ad1:', ':ad1:', 'countries/ad1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cn2:', ':cn2:', 'countries/cn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ki2:', ':ki2:', 'countries/ki2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tf2:', ':tf2:', 'countries/tf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ps2:', ':ps2:', 'countries/ps2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cd1:', ':cd1:', 'countries/cd1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':km2:', ':km2:', 'countries/km2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tj3:', ':tj3:', 'countries/tj3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ne3:', ':ne3:', 'countries/ne3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fi3:', ':fi3:', 'countries/fi3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':as1:', ':as1:', 'countries/as1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rw3:', ':rw3:', 'countries/rw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':to2:', ':to2:', 'countries/to2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mx1:', ':mx1:', 'countries/mx1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ws1:', ':ws1:', 'countries/ws1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hr2:', ':hr2:', 'countries/hr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':es2:', ':es2:', 'countries/es2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':es1:', ':es1:', 'countries/es1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lu1:', ':lu1:', 'countries/lu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':am3:', ':am3:', 'countries/am3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':th3:', ':th3:', 'countries/th3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sj2:', ':sj2:', 'countries/sj2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dm2:', ':dm2:', 'countries/dm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pg1:', ':pg1:', 'countries/pg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eh1:', ':eh1:', 'countries/eh1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zw1:', ':zw1:', 'countries/zw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nz3:', ':nz3:', 'countries/nz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vi2:', ':vi2:', 'countries/vi2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kg1:', ':kg1:', 'countries/kg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gd3:', ':gd3:', 'countries/gd3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gy2:', ':gy2:', 'countries/gy2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lb1:', ':lb1:', 'countries/lb1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ps3:', ':ps3:', 'countries/ps3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cd2:', ':cd2:', 'countries/cd2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':et2:', ':et2:', 'countries/et2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':il1:', ':il1:', 'countries/il1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sy2:', ':sy2:', 'countries/sy2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':al2:', ':al2:', 'countries/al2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cn1:', ':cn1:', 'countries/cn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gq3:', ':gq3:', 'countries/gq3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fam2:', ':fam2:', 'countries/fam2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sl3:', ':sl3:', 'countries/sl3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ee3:', ':ee3:', 'countries/ee3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gi2:', ':gi2:', 'countries/gi2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gf2:', ':gf2:', 'countries/gf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wf3:', ':wf3:', 'countries/wf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':iq2:', ':iq2:', 'countries/iq2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mp1:', ':mp1:', 'countries/mp1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kn1:', ':kn1:', 'countries/kn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gq1:', ':gq1:', 'countries/gq1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gw2:', ':gw2:', 'countries/gw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hk2:', ':hk2:', 'countries/hk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':au3:', ':au3:', 'countries/au3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lt2:', ':lt2:', 'countries/lt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':de1:', ':de1:', 'countries/de1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cs3:', ':cs3:', 'countries/cs3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':om1:', ':om1:', 'countries/om1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fr2:', ':fr2:', 'countries/fr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':do1:', ':do1:', 'countries/do1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lc2:', ':lc2:', 'countries/lc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jo1:', ':jo1:', 'countries/jo1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ph1:', ':ph1:', 'countries/ph1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cx2:', ':cx2:', 'countries/cx2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mh1:', ':mh1:', 'countries/mh1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lb2:', ':lb2:', 'countries/lb2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pk3:', ':pk3:', 'countries/pk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hr3:', ':hr3:', 'countries/hr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cm2:', ':cm2:', 'countries/cm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kh3:', ':kh3:', 'countries/kh3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':no3:', ':no3:', 'countries/no3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tg2:', ':tg2:', 'countries/tg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ro1:', ':ro1:', 'countries/ro1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':my3:', ':my3:', 'countries/my3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sv2:', ':sv2:', 'countries/sv2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bz2:', ':bz2:', 'countries/bz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':is1:', ':is1:', 'countries/is1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tm3:', ':tm3:', 'countries/tm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kh2:', ':kh2:', 'countries/kh2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ai3:', ':ai3:', 'countries/ai3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':er1:', ':er1:', 'countries/er1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':me3:', ':me3:', 'countries/me3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':no2:', ':no2:', 'countries/no2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lu2:', ':lu2:', 'countries/lu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':my2:', ':my2:', 'countries/my2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bb3:', ':bb3:', 'countries/bb3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pt2:', ':pt2:', 'countries/pt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ir1:', ':ir1:', 'countries/ir1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ht2:', ':ht2:', 'countries/ht2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mm2:', ':mm2:', 'countries/mm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sco2:', ':sco2:', 'countries/sco2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pl1:', ':pl1:', 'countries/pl1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':il2:', ':il2:', 'countries/il2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rw1:', ':rw1:', 'countries/rw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eg1:', ':eg1:', 'countries/eg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':iq3:', ':iq3:', 'countries/iq3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':me1:', ':me1:', 'countries/me1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sz3:', ':sz3:', 'countries/sz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pe2:', ':pe2:', 'countries/pe2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hm1:', ':hm1:', 'countries/hm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ca2:', ':ca2:', 'countries/ca2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ne2:', ':ne2:', 'countries/ne2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mz2:', ':mz2:', 'countries/mz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ml3:', ':ml3:', 'countries/ml3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ae2:', ':ae2:', 'countries/ae2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mu3:', ':mu3:', 'countries/mu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':at2:', ':at2:', 'countries/at2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vc3:', ':vc3:', 'countries/vc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tr3:', ':tr3:', 'countries/tr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bv1:', ':bv1:', 'countries/bv1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ly2:', ':ly2:', 'countries/ly2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tv2:', ':tv2:', 'countries/tv2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':na3:', ':na3:', 'countries/na3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':by2:', ':by2:', 'countries/by2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ml1:', ':ml1:', 'countries/ml1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':so1:', ':so1:', 'countries/so1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mx3:', ':mx3:', 'countries/mx3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ws2:', ':ws2:', 'countries/ws2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lk2:', ':lk2:', 'countries/lk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kp3:', ':kp3:', 'countries/kp3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gh2:', ':gh2:', 'countries/gh2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':et3:', ':et3:', 'countries/et3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bo1:', ':bo1:', 'countries/bo1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sn3:', ':sn3:', 'countries/sn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fam1:', ':fam1:', 'countries/fam1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nr2:', ':nr2:', 'countries/nr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ch1:', ':ch1:', 'countries/ch1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':uy1:', ':uy1:', 'countries/uy1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ye3:', ':ye3:', 'countries/ye3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':li1:', ':li1:', 'countries/li1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gy3:', ':gy3:', 'countries/gy3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sc1:', ':sc1:', 'countries/sc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':la2:', ':la2:', 'countries/la2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':an2:', ':an2:', 'countries/an2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kg3:', ':kg3:', 'countries/kg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pr2:', ':pr2:', 'countries/pr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cr1:', ':cr1:', 'countries/cr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dk2:', ':dk2:', 'countries/dk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ao1:', ':ao1:', 'countries/ao1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ms3:', ':ms3:', 'countries/ms3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eg2:', ':eg2:', 'countries/eg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':si3:', ':si3:', 'countries/si3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cg1:', ':cg1:', 'countries/cg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':se3:', ':se3:', 'countries/se3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ca1:', ':ca1:', 'countries/ca1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lu3:', ':lu3:', 'countries/lu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':py2:', ':py2:', 'countries/py2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fo2:', ':fo2:', 'countries/fo2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vu1:', ':vu1:', 'countries/vu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cn3:', ':cn3:', 'countries/cn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cy1:', ':cy1:', 'countries/cy1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tf1:', ':tf1:', 'countries/tf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mc3:', ':mc3:', 'countries/mc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vn1:', ':vn1:', 'countries/vn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jm3:', ':jm3:', 'countries/jm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':is2:', ':is2:', 'countries/is2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sy3:', ':sy3:', 'countries/sy3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lc1:', ':lc1:', 'countries/lc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mr2:', ':mr2:', 'countries/mr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ly1:', ':ly1:', 'countries/ly1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mn3:', ':mn3:', 'countries/mn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':si1:', ':si1:', 'countries/si1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':be2:', ':be2:', 'countries/be2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gl3:', ':gl3:', 'countries/gl3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':uy2:', ':uy2:', 'countries/uy2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':br1:', ':br1:', 'countries/br1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mr3:', ':mr3:', 'countries/mr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':td1:', ':td1:', 'countries/td1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vi3:', ':vi3:', 'countries/vi3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mh3:', ':mh3:', 'countries/mh3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nz2:', ':nz2:', 'countries/nz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':do2:', ':do2:', 'countries/do2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wal1:', ':wal1:', 'countries/wal1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tg3:', ':tg3:', 'countries/tg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ga3:', ':ga3:', 'countries/ga3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gs2:', ':gs2:', 'countries/gs2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bo2:', ':bo2:', 'countries/bo2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nc3:', ':nc3:', 'countries/nc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pe1:', ':pe1:', 'countries/pe1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vu2:', ':vu2:', 'countries/vu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lv1:', ':lv1:', 'countries/lv1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lr1:', ':lr1:', 'countries/lr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eng2:', ':eng2:', 'countries/eng2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kr1:', ':kr1:', 'countries/kr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pt1:', ':pt1:', 'countries/pt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':do3:', ':do3:', 'countries/do3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bg2:', ':bg2:', 'countries/bg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bt1:', ':bt1:', 'countries/bt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':um3:', ':um3:', 'countries/um3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bh2:', ':bh2:', 'countries/bh2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':de3:', ':de3:', 'countries/de3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ax2:', ':ax2:', 'countries/ax2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cv3:', ':cv3:', 'countries/cv3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ni1:', ':ni1:', 'countries/ni1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pr1:', ':pr1:', 'countries/pr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':de2:', ':de2:', 'countries/de2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bn1:', ':bn1:', 'countries/bn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cg3:', ':cg3:', 'countries/cg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ph3:', ':ph3:', 'countries/ph3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ye1:', ':ye1:', 'countries/ye1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ni3:', ':ni3:', 'countries/ni3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':er3:', ':er3:', 'countries/er3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sm1:', ':sm1:', 'countries/sm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ge2:', ':ge2:', 'countries/ge2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tc2:', ':tc2:', 'countries/tc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':qa1:', ':qa1:', 'countries/qa1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nr1:', ':nr1:', 'countries/nr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kr2:', ':kr2:', 'countries/kr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cc1:', ':cc1:', 'countries/cc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':be1:', ':be1:', 'countries/be1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':by3:', ':by3:', 'countries/by3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gl2:', ':gl2:', 'countries/gl2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':er2:', ':er2:', 'countries/er2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':la1:', ':la1:', 'countries/la1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sh1:', ':sh1:', 'countries/sh1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tw3:', ':tw3:', 'countries/tw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gf1:', ':gf1:', 'countries/gf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pr3:', ':pr3:', 'countries/pr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ke2:', ':ke2:', 'countries/ke2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':km3:', ':km3:', 'countries/km3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sa2:', ':sa2:', 'countries/sa2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':md3:', ':md3:', 'countries/md3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cu2:', ':cu2:', 'countries/cu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ht1:', ':ht1:', 'countries/ht1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gu1:', ':gu1:', 'countries/gu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kz1:', ':kz1:', 'countries/kz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':in2:', ':in2:', 'countries/in2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tr1:', ':tr1:', 'countries/tr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fk1:', ':fk1:', 'countries/fk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sd2:', ':sd2:', 'countries/sd2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':no1:', ':no1:', 'countries/no1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pk2:', ':pk2:', 'countries/pk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ua1:', ':ua1:', 'countries/ua1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':st1:', ':st1:', 'countries/st1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ch3:', ':ch3:', 'countries/ch3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gp3:', ':gp3:', 'countries/gp3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ci3:', ':ci3:', 'countries/ci3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pa3:', ':pa3:', 'countries/pa3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bj3:', ':bj3:', 'countries/bj3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ru3:', ':ru3:', 'countries/ru3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ax1:', ':ax1:', 'countries/ax1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mv1:', ':mv1:', 'countries/mv1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rs1:', ':rs1:', 'countries/rs1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sv1:', ':sv1:', 'countries/sv1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cl2:', ':cl2:', 'countries/cl2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ar1:', ':ar1:', 'countries/ar1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bw1:', ':bw1:', 'countries/bw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':se2:', ':se2:', 'countries/se2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cz2:', ':cz2:', 'countries/cz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sg2:', ':sg2:', 'countries/sg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bm3:', ':bm3:', 'countries/bm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pg3:', ':pg3:', 'countries/pg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mm1:', ':mm1:', 'countries/mm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tn3:', ':tn3:', 'countries/tn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tz3:', ':tz3:', 'countries/tz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vg1:', ':vg1:', 'countries/vg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dm3:', ':dm3:', 'countries/dm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ir3:', ':ir3:', 'countries/ir3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vc1:', ':vc1:', 'countries/vc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':at3:', ':at3:', 'countries/at3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sb1:', ':sb1:', 'countries/sb1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sr3:', ':sr3:', 'countries/sr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ck1:', ':ck1:', 'countries/ck1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ug1:', ':ug1:', 'countries/ug1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':et1:', ':et1:', 'countries/et1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hu3:', ':hu3:', 'countries/hu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vg2:', ':vg2:', 'countries/vg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':us1:', ':us1:', 'countries/us1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':so2:', ':so2:', 'countries/so2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kz2:', ':kz2:', 'countries/kz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fj3:', ':fj3:', 'countries/fj3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tn2:', ':tn2:', 'countries/tn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bv2:', ':bv2:', 'countries/bv2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dk1:', ':dk1:', 'countries/dk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cm3:', ':cm3:', 'countries/cm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':al3:', ':al3:', 'countries/al3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sco1:', ':sco1:', 'countries/sco1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fr3:', ':fr3:', 'countries/fr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':aw2:', ':aw2:', 'countries/aw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gt2:', ':gt2:', 'countries/gt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bo3:', ':bo3:', 'countries/bo3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mu1:', ':mu1:', 'countries/mu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':la3:', ':la3:', 'countries/la3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eg3:', ':eg3:', 'countries/eg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mz1:', ':mz1:', 'countries/mz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dj1:', ':dj1:', 'countries/dj1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bv3:', ':bv3:', 'countries/bv3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pl3:', ':pl3:', 'countries/pl3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':it2:', ':it2:', 'countries/it2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ck2:', ':ck2:', 'countries/ck2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tj2:', ':tj2:', 'countries/tj2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bs1:', ':bs1:', 'countries/bs1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ky2:', ':ky2:', 'countries/ky2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mc1:', ':mc1:', 'countries/mc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cx1:', ':cx1:', 'countries/cx1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':io3:', ':io3:', 'countries/io3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pn2:', ':pn2:', 'countries/pn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kz3:', ':kz3:', 'countries/kz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':id1:', ':id1:', 'countries/id1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':am2:', ':am2:', 'countries/am2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gh1:', ':gh1:', 'countries/gh1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ai2:', ':ai2:', 'countries/ai2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gh3:', ':gh3:', 'countries/gh3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jm2:', ':jm2:', 'countries/jm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bh3:', ':bh3:', 'countries/bh3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':is3:', ':is3:', 'countries/is3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bb1:', ':bb1:', 'countries/bb1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gi3:', ':gi3:', 'countries/gi3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pn3:', ':pn3:', 'countries/pn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sn2:', ':sn2:', 'countries/sn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gd1:', ':gd1:', 'countries/gd1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ae3:', ':ae3:', 'countries/ae3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':np3:', ':np3:', 'countries/np3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bs3:', ':bs3:', 'countries/bs3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gm2:', ':gm2:', 'countries/gm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cz3:', ':cz3:', 'countries/cz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sg3:', ':sg3:', 'countries/sg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':si2:', ':si2:', 'countries/si2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nr3:', ':nr3:', 'countries/nr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tz1:', ':tz1:', 'countries/tz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pm2:', ':pm2:', 'countries/pm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cf3:', ':cf3:', 'countries/cf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ua3:', ':ua3:', 'countries/ua3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':np2:', ':np2:', 'countries/np2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nc1:', ':nc1:', 'countries/nc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':by1:', ':by1:', 'countries/by1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':td2:', ':td2:', 'countries/td2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ne1:', ':ne1:', 'countries/ne1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bj2:', ':bj2:', 'countries/bj2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ug2:', ':ug2:', 'countries/ug2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ly3:', ':ly3:', 'countries/ly3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nl3:', ':nl3:', 'countries/nl3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ve1:', ':ve1:', 'countries/ve1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ki1:', ':ki1:', 'countries/ki1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ms2:', ':ms2:', 'countries/ms2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kh1:', ':kh1:', 'countries/kh1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':az3:', ':az3:', 'countries/az3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tt3:', ':tt3:', 'countries/tt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':re2:', ':re2:', 'countries/re2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ma3:', ':ma3:', 'countries/ma3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':yt3:', ':yt3:', 'countries/yt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tt1:', ':tt1:', 'countries/tt1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ax3:', ':ax3:', 'countries/ax3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gd2:', ':gd2:', 'countries/gd2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tn1:', ':tn1:', 'countries/tn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gp1:', ':gp1:', 'countries/gp1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sa3:', ':sa3:', 'countries/sa3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ni2:', ':ni2:', 'countries/ni2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lb3:', ':lb3:', 'countries/lb3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eh2:', ':eh2:', 'countries/eh2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pf3:', ':pf3:', 'countries/pf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mn2:', ':mn2:', 'countries/mn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fm2:', ':fm2:', 'countries/fm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ao2:', ':ao2:', 'countries/ao2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':qa2:', ':qa2:', 'countries/qa2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cm1:', ':cm1:', 'countries/cm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tg1:', ':tg1:', 'countries/tg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lr3:', ':lr3:', 'countries/lr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hu2:', ':hu2:', 'countries/hu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':um2:', ':um2:', 'countries/um2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ba1:', ':ba1:', 'countries/ba1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ky3:', ':ky3:', 'countries/ky3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pg2:', ':pg2:', 'countries/pg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sc2:', ':sc2:', 'countries/sc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fam3:', ':fam3:', 'countries/fam3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ge1:', ':ge1:', 'countries/ge1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ec1:', ':ec1:', 'countries/ec1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bd2:', ':bd2:', 'countries/bd2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':td3:', ':td3:', 'countries/td3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mm3:', ':mm3:', 'countries/mm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bw3:', ':bw3:', 'countries/bw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':us3:', ':us3:', 'countries/us3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':io1:', ':io1:', 'countries/io1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nu3:', ':nu3:', 'countries/nu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sm2:', ':sm2:', 'countries/sm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hk1:', ':hk1:', 'countries/hk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':co2:', ':co2:', 'countries/co2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ke3:', ':ke3:', 'countries/ke3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pw3:', ':pw3:', 'countries/pw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':co1:', ':co1:', 'countries/co1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hu1:', ':hu1:', 'countries/hu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mg2:', ':mg2:', 'countries/mg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':qa3:', ':qa3:', 'countries/qa3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kw1:', ':kw1:', 'countries/kw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tw2:', ':tw2:', 'countries/tw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tc3:', ':tc3:', 'countries/tc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':th1:', ':th1:', 'countries/th1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':md1:', ':md1:', 'countries/md1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bi3:', ':bi3:', 'countries/bi3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mq1:', ':mq1:', 'countries/mq1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tl3:', ':tl3:', 'countries/tl3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tt2:', ':tt2:', 'countries/tt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sj1:', ':sj1:', 'countries/sj1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ye2:', ':ye2:', 'countries/ye2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':va2:', ':va2:', 'countries/va2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ht3:', ':ht3:', 'countries/ht3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cr2:', ':cr2:', 'countries/cr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vc2:', ':vc2:', 'countries/vc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ps1:', ':ps1:', 'countries/ps1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tm1:', ':tm1:', 'countries/tm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ck3:', ':ck3:', 'countries/ck3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nf3:', ':nf3:', 'countries/nf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rs2:', ':rs2:', 'countries/rs2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mu2:', ':mu2:', 'countries/mu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fk2:', ':fk2:', 'countries/fk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gm1:', ':gm1:', 'countries/gm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ng3:', ':ng3:', 'countries/ng3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':an3:', ':an3:', 'countries/an3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gy1:', ':gy1:', 'countries/gy1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jm1:', ':jm1:', 'countries/jm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pn1:', ':pn1:', 'countries/pn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bt3:', ':bt3:', 'countries/bt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tz2:', ':tz2:', 'countries/tz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mx2:', ':mx2:', 'countries/mx2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gp2:', ':gp2:', 'countries/gp2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sm3:', ':sm3:', 'countries/sm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fo1:', ':fo1:', 'countries/fo1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':uy3:', ':uy3:', 'countries/uy3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mp3:', ':mp3:', 'countries/mp3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ng1:', ':ng1:', 'countries/ng1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ga1:', ':ga1:', 'countries/ga1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pa1:', ':pa1:', 'countries/pa1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':as2:', ':as2:', 'countries/as2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':be3:', ':be3:', 'countries/be3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cy3:', ':cy3:', 'countries/cy3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':af1:', ':af1:', 'countries/af1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fj2:', ':fj2:', 'countries/fj2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dj3:', ':dj3:', 'countries/dj3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mo1:', ':mo1:', 'countries/mo1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nu1:', ':nu1:', 'countries/nu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mc2:', ':mc2:', 'countries/mc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hm2:', ':hm2:', 'countries/hm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kp2:', ':kp2:', 'countries/kp2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':za1:', ':za1:', 'countries/za1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vn3:', ':vn3:', 'countries/vn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hn3:', ':hn3:', 'countries/hn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pf1:', ':pf1:', 'countries/pf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gs1:', ':gs1:', 'countries/gs1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ir2:', ':ir2:', 'countries/ir2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sl2:', ':sl2:', 'countries/sl2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jp3:', ':jp3:', 'countries/jp3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wal2:', ':wal2:', 'countries/wal2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sy1:', ':sy1:', 'countries/sy1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':aw3:', ':aw3:', 'countries/aw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':rs3:', ':rs3:', 'countries/rs3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ky1:', ':ky1:', 'countries/ky1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vn2:', ':vn2:', 'countries/vn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sr1:', ':sr1:', 'countries/sr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mv2:', ':mv2:', 'countries/mv2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':am1:', ':am1:', 'countries/am1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ad2:', ':ad2:', 'countries/ad2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bg1:', ':bg1:', 'countries/bg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':km1:', ':km1:', 'countries/km1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dj2:', ':dj2:', 'countries/dj2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pw2:', ':pw2:', 'countries/pw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hr1:', ':hr1:', 'countries/hr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bd1:', ':bd1:', 'countries/bd1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pe3:', ':pe3:', 'countries/pe3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ci2:', ':ci2:', 'countries/ci2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':om2:', ':om2:', 'countries/om2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mw2:', ':mw2:', 'countries/mw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':st2:', ':st2:', 'countries/st2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sh3:', ':sh3:', 'countries/sh3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ml2:', ':ml2:', 'countries/ml2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':at1:', ':at1:', 'countries/at1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gr3:', ':gr3:', 'countries/gr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':va1:', ':va1:', 'countries/va1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mr1:', ':mr1:', 'countries/mr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ci1:', ':ci1:', 'countries/ci1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':af3:', ':af3:', 'countries/af3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':co3:', ':co3:', 'countries/co3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fr1:', ':fr1:', 'countries/fr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sc3:', ':sc3:', 'countries/sc3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fm3:', ':fm3:', 'countries/fm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hn2:', ':hn2:', 'countries/hn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ch2:', ':ch2:', 'countries/ch2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gn2:', ':gn2:', 'countries/gn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pt3:', ':pt3:', 'countries/pt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ma1:', ':ma1:', 'countries/ma1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':uz2:', ':uz2:', 'countries/uz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gn3:', ':gn3:', 'countries/gn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cy2:', ':cy2:', 'countries/cy2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':iq1:', ':iq1:', 'countries/iq1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gw3:', ':gw3:', 'countries/gw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zm1:', ':zm1:', 'countries/zm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pk1:', ':pk1:', 'countries/pk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kp1:', ':kp1:', 'countries/kp1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gm3:', ':gm3:', 'countries/gm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bj1:', ':bj1:', 'countries/bj1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sk1:', ':sk1:', 'countries/sk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gu2:', ':gu2:', 'countries/gu2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ie2:', ':ie2:', 'countries/ie2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lt3:', ':lt3:', 'countries/lt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':yt2:', ':yt2:', 'countries/yt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ls3:', ':ls3:', 'countries/ls3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ag3:', ':ag3:', 'countries/ag3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mk3:', ':mk3:', 'countries/mk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kr3:', ':kr3:', 'countries/kr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eng1:', ':eng1:', 'countries/eng1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ma2:', ':ma2:', 'countries/ma2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ee1:', ':ee1:', 'countries/ee1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':so3:', ':so3:', 'countries/so3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ng2:', ':ng2:', 'countries/ng2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ag1:', ':ag1:', 'countries/ag1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':re3:', ':re3:', 'countries/re3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sk2:', ':sk2:', 'countries/sk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kw2:', ':kw2:', 'countries/kw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':py1:', ':py1:', 'countries/py1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cr3:', ':cr3:', 'countries/cr3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zw2:', ':zw2:', 'countries/zw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nl2:', ':nl2:', 'countries/nl2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ba3:', ':ba3:', 'countries/ba3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lk1:', ':lk1:', 'countries/lk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mz3:', ':mz3:', 'countries/mz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fm1:', ':fm1:', 'countries/fm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ro3:', ':ro3:', 'countries/ro3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pa2:', ':pa2:', 'countries/pa2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gl1:', ':gl1:', 'countries/gl1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sh2:', ':sh2:', 'countries/sh2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cx3:', ':cx3:', 'countries/cx3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jp1:', ':jp1:', 'countries/jp1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ee2:', ':ee2:', 'countries/ee2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mw1:', ':mw1:', 'countries/mw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pm1:', ':pm1:', 'countries/pm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cc2:', ':cc2:', 'countries/cc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':th2:', ':th2:', 'countries/th2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mh2:', ':mh2:', 'countries/mh2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':me2:', ':me2:', 'countries/me2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ki3:', ':ki3:', 'countries/ki3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bd3:', ':bd3:', 'countries/bd3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ws3:', ':ws3:', 'countries/ws3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ms1:', ':ms1:', 'countries/ms1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pm3:', ':pm3:', 'countries/pm3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ec2:', ':ec2:', 'countries/ec2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':il3:', ':il3:', 'countries/il3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jp2:', ':jp2:', 'countries/jp2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tr2:', ':tr2:', 'countries/tr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':in1:', ':in1:', 'countries/in1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gr1:', ':gr1:', 'countries/gr1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ca3:', ':ca3:', 'countries/ca3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fi1:', ':fi1:', 'countries/fi1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mk1:', ':mk1:', 'countries/mk1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tv3:', ':tv3:', 'countries/tv3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bb2:', ':bb2:', 'countries/bb2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ec3:', ':ec3:', 'countries/ec3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sb2:', ':sb2:', 'countries/sb2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kn3:', ':kn3:', 'countries/kn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mv3:', ':mv3:', 'countries/mv3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':br3:', ':br3:', 'countries/br3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lk3:', ':lk3:', 'countries/lk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':as3:', ':as3:', 'countries/as3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bf3:', ':bf3:', 'countries/bf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cl1:', ':cl1:', 'countries/cl1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':za2:', ':za2:', 'countries/za2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ls1:', ':ls1:', 'countries/ls1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':aw1:', ':aw1:', 'countries/aw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bh1:', ':bh1:', 'countries/bh1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':it1:', ':it1:', 'countries/it1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dk3:', ':dk3:', 'countries/dk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lv3:', ':lv3:', 'countries/lv3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ro2:', ':ro2:', 'countries/ro2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':it3:', ':it3:', 'countries/it3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mt3:', ':mt3:', 'countries/mt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cf1:', ':cf1:', 'countries/cf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':st3:', ':st3:', 'countries/st3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gb1:', ':gb1:', 'countries/gb1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ae1:', ':ae1:', 'countries/ae1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bt2:', ':bt2:', 'countries/bt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gf3:', ':gf3:', 'countries/gf3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mg1:', ':mg1:', 'countries/mg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cs2:', ':cs2:', 'countries/cs2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pl2:', ':pl2:', 'countries/pl2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':zm2:', ':zm2:', 'countries/zm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nc2:', ':nc2:', 'countries/nc2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kn2:', ':kn2:', 'countries/kn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tl2:', ':tl2:', 'countries/tl2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gr2:', ':gr2:', 'countries/gr2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mt2:', ':mt2:', 'countries/mt2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mt2.pn:', ':mt2.pn:', 'countries/mt2.pn.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sg1:', ':sg1:', 'countries/sg1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fi2:', ':fi2:', 'countries/fi2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gw1:', ':gw1:', 'countries/gw1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gb3:', ':gb3:', 'countries/gb3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ge3:', ':ge3:', 'countries/ge3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':py3:', ':py3:', 'countries/py3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gt3:', ':gt3:', 'countries/gt3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tv1:', ':tv1:', 'countries/tv1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':uz1:', ':uz1:', 'countries/uz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cv1:', ':cv1:', 'countries/cv1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ar2:', ':ar2:', 'countries/ar2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vg3:', ':vg3:', 'countries/vg3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':lv2:', ':lv2:', 'countries/lv2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sl1:', ':sl1:', 'countries/sl1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gu3:', ':gu3:', 'countries/gu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kw3:', ':kw3:', 'countries/kw3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':se1:', ':se1:', 'countries/se1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dm1:', ':dm1:', 'countries/dm1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bn3:', ':bn3:', 'countries/bn3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cf2:', ':cf2:', 'countries/cf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bm2:', ':bm2:', 'countries/bm2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sj3:', ':sj3:', 'countries/sj3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cd3:', ':cd3:', 'countries/cd3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':gn1:', ':gn1:', 'countries/gn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bn2:', ':bn2:', 'countries/bn2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':fo3:', ':fo3:', 'countries/fo3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':id2:', ':id2:', 'countries/id2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dz2:', ':dz2:', 'countries/dz2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nf1:', ':nf1:', 'countries/nf1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':nz1:', ':nz1:', 'countries/nz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cg2:', ':cg2:', 'countries/cg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':kg2:', ':kg2:', 'countries/kg2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ai1:', ':ai1:', 'countries/ai1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bi2:', ':bi2:', 'countries/bi2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ug3:', ':ug3:', 'countries/ug3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cu1:', ':cu1:', 'countries/cu1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':an1:', ':an1:', 'countries/an1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':va3:', ':va3:', 'countries/va3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':uz3:', ':uz3:', 'countries/uz3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mo3:', ':mo3:', 'countries/mo3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':na1:', ':na1:', 'countries/na1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':au1:', ':au1:', 'countries/au1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':eng3:', ':eng3:', 'countries/eng3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ru1:', ':ru1:', 'countries/ru1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':pf2:', ':pf2:', 'countries/pf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ph2:', ':ph2:', 'countries/ph2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hn1:', ':hn1:', 'countries/hn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':li2:', ':li2:', 'countries/li2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tk2:', ':tk2:', 'countries/tk2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':tc1:', ':tc1:', 'countries/tc1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':wf2:', ':wf2:', 'countries/wf2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':re1:', ':re1:', 'countries/re1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':ls2:', ':ls2:', 'countries/ls2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':af2:', ':af2:', 'countries/af2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':hk3:', ':hk3:', 'countries/hk3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cu3:', ':cu3:', 'countries/cu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':to3:', ':to3:', 'countries/to3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':bw2:', ':bw2:', 'countries/bw2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':jo3:', ':jo3:', 'countries/jo3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':dz1:', ':dz1:', 'countries/dz1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':in3:', ':in3:', 'countries/in3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mn1:', ':mn1:', 'countries/mn1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cv2:', ':cv2:', 'countries/cv2.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':vu3:', ':vu3:', 'countries/vu3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':sv3:', ':sv3:', 'countries/sv3.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':cs1:', ':cs1:', 'countries/cs1.png');
INSERT INTO __SCHEMA__.smileys (text,text_alternative,url) VALUES (':mp2:', ':mp2:', 'countries/mp2.png');
